export const Features = {
  WASH_AND_DRY: "Exterior organic wash & dry",
  GLASS_CLEAN: "All glass cleaned",
  RIMS_AND_TIRES_CLEAN: "Rims and tires cleaned",
  TIRES_SHINED: "Tires shined",
  GRIME_REMOVED: "Grime removed",
  SEATS_VACUUMED: "Seats vacuumed/wiped",
  TRASH_REMOVED: "Trash removed",
  DETAIL_BRUSHING: "Detail brushing for deep cleaning",
  SEATS_AND_FLOOR_SHAMPOO: "Seats and floor shampoo",
  CARPET_DEODORIZING: "Carpet deodorizing",
  WAX: "Wax",
};

export const AllPackageFeatures = [
  Features.WASH_AND_DRY,
  Features.GLASS_CLEAN,
  Features.RIMS_AND_TIRES_CLEAN,
  Features.TIRES_SHINED,
  Features.GRIME_REMOVED,
  Features.SEATS_VACUUMED,
  Features.TRASH_REMOVED,
  Features.DETAIL_BRUSHING,
  Features.SEATS_AND_FLOOR_SHAMPOO,
  Features.CARPET_DEODORIZING,
  Features.WAX,
];

export const PackagesFeatures = {
  STANDARD: [
    Features.WASH_AND_DRY,
    Features.GLASS_CLEAN,
    Features.RIMS_AND_TIRES_CLEAN,
    Features.TIRES_SHINED,
    Features.GRIME_REMOVED,
    Features.SEATS_VACUUMED,
    Features.TRASH_REMOVED,
  ],
  DELUXE: [
    Features.WASH_AND_DRY,
    Features.GLASS_CLEAN,
    Features.RIMS_AND_TIRES_CLEAN,
    Features.TIRES_SHINED,
    Features.GRIME_REMOVED,
    Features.SEATS_VACUUMED,
    Features.TRASH_REMOVED,
    Features.DETAIL_BRUSHING,
    Features.SEATS_AND_FLOOR_SHAMPOO,
  ],
  PREMIUM: [
    Features.WASH_AND_DRY,
    Features.GLASS_CLEAN,
    Features.RIMS_AND_TIRES_CLEAN,
    Features.TIRES_SHINED,
    Features.GRIME_REMOVED,
    Features.SEATS_VACUUMED,
    Features.TRASH_REMOVED,
    Features.DETAIL_BRUSHING,
    Features.SEATS_AND_FLOOR_SHAMPOO,
    Features.CARPET_DEODORIZING,
    Features.WAX,
  ],
};
